# -*- coding: utf-8 -*-

import cv2
import numpy as np
img=cv2.imread('/Users/yizeliu/Downloads/OpenCV_homework/Test_images/baboon.jpg')
img1=cv2.imread('/Users/yizeliu/Downloads/OpenCV_homework/Test_images/rice_grains.jpg')
img2=cv2.imread('/Users/yizeliu/Downloads/OpenCV_homework/Test_images/Lenna.png')
img3=cv2.imread('/Users/yizeliu/Downloads/OpenCV_homework/Test_images/coins.png')
img4=cv2.imread('/Users/yizeliu/Downloads/OpenCV_homework/Test_images/barbara.png')
img5=cv2.imread('/Users/yizeliu/Downloads/OpenCV_homework/Test_images/cameraman.png')
f = open("pixelResult.txt", "w")
f.write("baboon")
f.write(str(img[20,25]))
YCrCb=cv2.cvtColor(img,cv2.COLOR_BGR2YCrCb)
f.write(str(YCrCb[20,25]))
hsv=cv2.cvtColor(img,cv2.COLOR_BGR2HSV)
f.write(str(hsv[20,25]))
f.write("rice_grains")
f.write(str(img1[20,25]))
YCrCb1=cv2.cvtColor(img1,cv2.COLOR_BGR2YCrCb)
f.write(str(YCrCb1[20,25]))
hsv1=cv2.cvtColor(img1,cv2.COLOR_BGR2HSV)
f.write(str(hsv1[20,25]))
f.write("Lenna")
f.write(str(img2[20,25]))
YCrCb2=cv2.cvtColor(img2,cv2.COLOR_BGR2YCrCb)
f.write(str(YCrCb2[20,25]))
hsv2=cv2.cvtColor(img2,cv2.COLOR_BGR2HSV)
f.write(str(hsv2[20,25]))
f.write("coins")
f.write(str(img3[20,25]))
YCrCb3=cv2.cvtColor(img3,cv2.COLOR_BGR2YCrCb)
f.write(str(YCrCb3[20,25]))
hsv3=cv2.cvtColor(img3,cv2.COLOR_BGR2HSV)
f.write(str(hsv3[20,25]))
f.write("barbara")
f.write(str(img4[20,25]))
YCrCb4=cv2.cvtColor(img4,cv2.COLOR_BGR2YCrCb)
f.write(str(YCrCb4[20,25]))
hsv4=cv2.cvtColor(img4,cv2.COLOR_BGR2HSV)
f.write(str(hsv4[20,25]))
f.write("cameraman")
f.write(str(img5[20,25]))
YCrCb5=cv2.cvtColor(img5,cv2.COLOR_BGR2YCrCb)
f.write(str(YCrCb5[20,25]))
hsv5=cv2.cvtColor(img5,cv2.COLOR_BGR2HSV)
f.write(str(hsv5[20,25]))